In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df1 = pd.read_csv("Bengaluru_House_Data.csv")
df1.head()

area_type   availability                  location       size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK   
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom   
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK   
3  Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK   
4  Super built-up  Area  Ready To Move                  Kothanur      2 BHK   

   society total_sqft  bath  balcony   price  
0  Coomee        1056   2.0      1.0   39.07  
1  Theanmp       2600   5.0      3.0  120.00  
2      NaN       1440   2.0      3.0   62.00  
3  Soiewre       1521   3.0      1.0   95.00  
4      NaN       1200   2.0      1.0   51.00

In [3]:
df1.shape

(13320, 9)

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   area_type     13320 non-null  object 
 1   availability  13320 non-null  object 
 2   location      13319 non-null  object 
 3   size          13304 non-null  object 
 4   society       7818 non-null   object 
 5   total_sqft    13320 non-null  object 
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB


In [5]:
df1.describe()

bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [6]:
df2 = df1.drop(["area_type","availability","society"],axis=1)
df2.head()

location       size total_sqft  bath  balcony   price
0  Electronic City Phase II      2 BHK       1056   2.0      1.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0      3.0  120.00
2               Uttarahalli      3 BHK       1440   2.0      3.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0      1.0   95.00
4                  Kothanur      2 BHK       1200   2.0      1.0   51.00

In [7]:
df2.isnull().sum()

location        1
size           16
total_sqft      0
bath           73
balcony       609
price           0
dtype: int64

In [9]:
df2.balcony.value_counts()

2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: balcony, dtype: int64

In [19]:
df2.balcony.unique()

array([ 1.,  3., nan,  2.,  0.])

In [33]:
df2.balcony.replace(np.nan,1,inplace=True) #bit non-obvious replacement of the data

In [34]:
df2.balcony.unique()

array([1., 3., 2., 0.])

In [40]:
df2.isnull().sum()

location      0
size          0
total_sqft    0
bath          0
balcony       0
price         0
dtype: int64

In [36]:
df2.bath.unique()

array([ 2.,  5.,  3.,  4.,  6.,  1.,  9., nan,  8.,  7., 11., 10., 14.,
       27., 12., 16., 40., 15., 13., 18.])

In [37]:
df2.bath.replace(np.nan,2,inplace=True) #meadian value is 2 hence.

In [39]:
df2.dropna(inplace=True)

In [41]:
df2.shape

(13303, 6)

In [44]:
df2['size'].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '4 BHK', '6 Bedroom', '3 Bedroom',
       '1 BHK', '1 RK', '1 Bedroom', '8 Bedroom', '2 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', '9 Bedroom', '27 BHK', '10 Bedroom', '11 Bedroom',
       '10 BHK', '19 BHK', '16 BHK', '43 Bedroom', '14 BHK', '8 BHK',
       '12 Bedroom', '13 BHK', '18 Bedroom'], dtype=object)

In [46]:
df2['bhk'] = df2['size'].apply(lambda x: x.split()[0])
df2.drop(columns=['size'],axis=1,inplace=True)
df2.head()

location total_sqft  bath  balcony   price bhk
0  Electronic City Phase II       1056   2.0      1.0   39.07   2
1          Chikka Tirupathi       2600   5.0      3.0  120.00   4
2               Uttarahalli       1440   2.0      3.0   62.00   3
3        Lingadheeranahalli       1521   3.0      1.0   95.00   3
4                  Kothanur       1200   2.0      1.0   51.00   2

In [47]:
df2.total_sqft.unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [48]:
def is_float(x):
    try:
        float(x)
    except:
        return False
    return True

In [50]:
df2[~df2['total_sqft'].apply(is_float)].head(20)

location      total_sqft  bath  balcony    price bhk
30               Yelahanka     2100 - 2850   4.0      0.0  186.000   4
56             Devanahalli     3010 - 3410   2.0      1.0  192.000   4
81             Hennur Road     2957 - 3450   2.0      1.0  224.500   4
122                 Hebbal     3067 - 8156   4.0      0.0  477.000   4
137     8th Phase JP Nagar     1042 - 1105   2.0      0.0   54.005   2
165               Sarjapur     1145 - 1340   2.0      0.0   43.490   2
188               KR Puram     1015 - 1540   2.0      0.0   56.800   2
224            Devanahalli     1520 - 1740   2.0      1.0   74.820   3
410                Kengeri  34.46Sq. Meter   1.0      0.0   18.500   1
549            Hennur Road     1195 - 1440   2.0      0.0   63.770   2
648                Arekere       4125Perch   9.0      1.0  265.000   9
661              Yelahanka     1120 - 1145   2.0      0.0   48.130   2
669               JP Nagar     4400 - 6640   2.0      1.0  375.000   5
672           Bettahalsoor     3090 - 5002   4.0      0.0  445.000   4
702               JP Nagar     4400 - 6800   2.0      1.0  548.500   5
772  Banashankari Stage VI     1160 - 1195   2.0      0.0   59.935   2
775           Basavanagara   1000Sq. Meter   2.0      1.0   93.000   1
801               JP Nagar     4000 - 5249   2.0      1.0  453.000   4
850      Bannerghatta Road     1115 - 1130   2.0      0.0   58.935   2
872      Singapura Village   1100Sq. Yards   2.0      1.0   45.000   2

In [53]:
def convert_sqft_to_num(x):
    tokens = x.split('-')
    if len(tokens)==2:
        return ((float(tokens[0])+float(tokens[1]))/2)
    try:
        return float(x)
    except:
        return None

In [54]:
df2.total_sqft = df2['total_sqft'].apply(convert_sqft_to_num)

In [58]:
df2[df2['total_sqft'].apply(is_float)].head(20)

location  total_sqft  bath  balcony   price bhk
0   Electronic City Phase II      1056.0   2.0      1.0   39.07   2
1           Chikka Tirupathi      2600.0   5.0      3.0  120.00   4
2                Uttarahalli      1440.0   2.0      3.0   62.00   3
3         Lingadheeranahalli      1521.0   3.0      1.0   95.00   3
4                   Kothanur      1200.0   2.0      1.0   51.00   2
5                 Whitefield      1170.0   2.0      1.0   38.00   2
6           Old Airport Road      2732.0   4.0      1.0  204.00   4
7               Rajaji Nagar      3300.0   4.0      1.0  600.00   4
8               Marathahalli      1310.0   3.0      1.0   63.25   3
9               Gandhi Bazar      1020.0   6.0      1.0  370.00   6
10                Whitefield      1800.0   2.0      2.0   70.00   3
11                Whitefield      2785.0   5.0      3.0  295.00   4
12        7th Phase JP Nagar      1000.0   2.0      1.0   38.00   2
13                 Gottigere      1100.0   2.0      2.0   40.00   2
14                  Sarjapur      2250.0   3.0      2.0  148.00   3
15               Mysore Road      1175.0   2.0      2.0   73.50   2
16             Bisuvanahalli      1180.0   3.0      2.0   48.00   3
17     Raja Rajeshwari Nagar      1540.0   3.0      3.0   60.00   3
18     Ramakrishnappa Layout      2770.0   4.0      2.0  290.00   3
19        Manayata Tech Park      1100.0   2.0      2.0   48.00   2

In [61]:
df2.total_sqft.isnull().sum()

46

In [62]:
df2.dropna(inplace=True)

In [64]:
df2.head(10)

location  total_sqft  bath  balcony   price bhk
0  Electronic City Phase II      1056.0   2.0      1.0   39.07   2
1          Chikka Tirupathi      2600.0   5.0      3.0  120.00   4
2               Uttarahalli      1440.0   2.0      3.0   62.00   3
3        Lingadheeranahalli      1521.0   3.0      1.0   95.00   3
4                  Kothanur      1200.0   2.0      1.0   51.00   2
5                Whitefield      1170.0   2.0      1.0   38.00   2
6          Old Airport Road      2732.0   4.0      1.0  204.00   4
7              Rajaji Nagar      3300.0   4.0      1.0  600.00   4
8              Marathahalli      1310.0   3.0      1.0   63.25   3
9              Gandhi Bazar      1020.0   6.0      1.0  370.00   6

In [65]:
df2.bhk = df2['bhk'].astype(float)

In [66]:
df2.describe()

total_sqft          bath       balcony         price           bhk
count  13257.000000  13257.000000  13257.000000  13257.000000  13257.000000
mean    1558.809175      2.688165      1.559629    112.471981      2.802670
std     1238.478935      1.336799      0.807475    149.092716      1.292117
min        1.000000      1.000000      0.000000      8.000000      1.000000
25%     1100.000000      2.000000      1.000000     50.000000      2.000000
50%     1275.000000      2.000000      2.000000     72.000000      3.000000
75%     1680.000000      3.000000      2.000000    120.000000      3.000000
max    52272.000000     40.000000      3.000000   3600.000000     43.000000

In [68]:
df3 = df2.copy()

In [69]:
df3['price_per_sqft'] = (df3['price']*100000)/df3['total_sqft']
df3.head()

location  total_sqft  bath  balcony   price  bhk  \
0  Electronic City Phase II      1056.0   2.0      1.0   39.07  2.0   
1          Chikka Tirupathi      2600.0   5.0      3.0  120.00  4.0   
2               Uttarahalli      1440.0   2.0      3.0   62.00  3.0   
3        Lingadheeranahalli      1521.0   3.0      1.0   95.00  3.0   
4                  Kothanur      1200.0   2.0      1.0   51.00  2.0   

   price_per_sqft  
0     3699.810606  
1     4615.384615  
2     4305.555556  
3     6245.890861  
4     4250.000000

In [71]:
len(df3.location.unique())

1298

In [80]:
pd.set_option("display.max_rows",None)

In [81]:
df3.location = df3.location.apply(lambda x:x.strip())

locations = df3.groupby('location')['location'].agg('count')
locations

location
1 Annasandrapalya                                       1
1 Giri Nagar                                            1
1 Immadihalli                                           1
1 Ramamurthy Nagar                                      1
12th cross srinivas nagar banshankari 3rd stage         1
1A Block Koramangala                                    1
1Channasandra                                           1
1Hanuman Nagar                                          1
1Hoysalanagar                                           1
1Kasavanhalli                                           1
1st Block BEL Layout                                    2
1st Block HBR Layout                                    3
1st Block HRBR Layout                                   8
1st Block Jayanagar                                    14
1st Block Koramangala                                  10
1st Phase JP Nagar                                     24
1st Stage Domlur                                        1
1st S

In [82]:
locations.sort_values(ascending=False)

location
Whitefield                                            538
Sarjapur  Road                                        397
Electronic City                                       304
Kanakpura Road                                        271
Thanisandra                                           236
Yelahanka                                             212
Uttarahalli                                           186
Hebbal                                                177
Marathahalli                                          175
Raja Rajeshwari Nagar                                 171
Hennur Road                                           152
Bannerghatta Road                                     151
7th Phase JP Nagar                                    148
Haralur Road                                          142
Electronic City Phase II                              132
Rajaji Nagar                                          107
Chandapura                                            100
Bella

In [85]:
less_than_10 = locations[locations<=10]

In [87]:
df3.location = df3.location.apply(lambda x : 'other' if x in less_than_10 else x)
len(df3.location.unique())

241